import Image from "next/image";

export default function Skills() {
  return (
    <div className="flex">
      <Image
        width="63"
        height="20"
        alt="Ember"
        src="https://img.shields.io/badge/-Ember-e04e39?style=flat-square&logo=emberdotjs&logoColor=white"
        unoptimized
      />
      <Image
        width="71"
        height="20"
        alt="Express"
        src="https://img.shields.io/badge/-Express-259dff?style=flat-square&logo=express&logoColor=white"
        unoptimized
      />
      <Image
        width="65"
        height="20"
        alt="Nodejs"
        src="https://img.shields.io/badge/-Nodejs-43853d?style=flat-square&logo=Node.js&logoColor=white"
        unoptimized
      />
      <Image
        width="85"
        height="20"
        alt="JavaScript"
        src="https://img.shields.io/badge/-JavaScript-f7df1e?style=flat-square&logo=javascript&logoColor=white"
        unoptimized
      />
      <Image
        width="87"
        height="20"
        alt="TypeScript"
        src="https://img.shields.io/badge/-TypeScript-007ACC?style=flat-square&logo=typescript&logoColor=white"
        unoptimized
      />
      <Image
        width="55"
        height="20"
        alt="Swift"
        src="https://img.shields.io/badge/-Swift-F05138?style=flat-square&logo=swift&logoColor=white"
        unoptimized
      />
      <Image
        width="53"
        height="20"
        alt="Rust"
        src="https://img.shields.io/badge/-Rust-F74C00?style=flat-square&logo=rust&logoColor=white"
        unoptimized
      />
      <Image
        width="81"
        height="20"
        alt="Bootstrap"
        src="https://img.shields.io/badge/-Bootstrap-7952B3?style=flat-square&logo=bootstrap&logoColor=white"
        unoptimized
      />
      <Image
        width="53"
        height="20"
        alt="Sass"
        src="https://img.shields.io/badge/-Sass-CC6699?style=flat-square&logo=sass&logoColor=white"
        unoptimized
      />
      <Image
        width="65"
        height="20"
        alt="HTML5"
        src="https://img.shields.io/badge/-HTML5-E34F26?style=flat-square&logo=html5&logoColor=white"
        unoptimized
      />
      <Image
        width="43"
        height="20"
        alt="git"
        src="https://img.shields.io/badge/-Git-F05032?style=flat-square&logo=git&logoColor=white"
        unoptimized
      />
      <Image
        width="109"
        height="20"
        alt="github actions"
        src="https://img.shields.io/badge/-Github_Actions-2088FF?style=flat-square&logo=github-actions&logoColor=white"
        unoptimized
      />
      <Image
        width="63"
        height="20"
        alt="Netlify"
        src="https://img.shields.io/badge/-Netlify-30C8C9?style=flat-square&logo=netlify&logoColor=white"
        unoptimized
      />
      <Image
        width="67"
        height="20"
        alt="Heroku"
        src="https://img.shields.io/badge/-Heroku-430098?style=flat-square&logo=heroku&logoColor=white"
        unoptimized
      />
      <Image
        width="151"
        height="20"
        alt="Google Cloud Platform"
        src="https://img.shields.io/badge/-Google_Cloud_Platform-1a73e8?style=flat-square&logo=google-cloud&logoColor=white"
        unoptimized
      />
      <Image
        width="71"
        height="20"
        alt="VSCode"
        src="https://img.shields.io/badge/-VSCode-0066B8?style=flat-square&logo=visualstudiocode&logoColor=white"
        unoptimized
      />
      <Image
        width="61"
        height="20"
        alt="Xcode"
        src="https://img.shields.io/badge/-Xcode-1890E6?style=flat-square&logo=xcode&logoColor=white"
        unoptimized
      />
      <Image
        width="79"
        height="20"
        alt="Insomnia"
        src="https://img.shields.io/badge/-Insomnia-5849BE?style=flat-square&logo=insomnia&logoColor=white"
        unoptimized
      />
      <Image
        width="69"
        height="20"
        alt="Prettier"
        src="https://img.shields.io/badge/-Prettier-F7B93E?style=flat-square&logo=prettier&logoColor=white"
        unoptimized
      />
      <Image
        width="53"
        height="20"
        alt="npm"
        src="https://img.shields.io/badge/-NPM-CB3837?style=flat-square&logo=npm&logoColor=white"
        unoptimized
      />
      <Image
        width="77"
        height="20"
        alt="Webpack"
        src="https://img.shields.io/badge/-Webpack-8DD6F9?style=flat-square&logo=webpack&logoColor=white"
        unoptimized
      />
      <Image
        width="65"
        height="20"
        alt="Sentry"
        src="https://img.shields.io/badge/-Sentry-301A38?style=flat-square&logo=sentry&logoColor=white"
        unoptimized
      />
      <Image
        width="59"
        height="20"
        alt="Percy"
        src="https://img.shields.io/badge/-Percy-B766BF?style=flat-square&logo=percy&logoColor=white"
        unoptimized
      />
      <Image
        width="65"
        height="20"
        alt="Algolia"
        src="https://img.shields.io/badge/-Algolia-5468FF?style=flat-square&logo=algolia&logoColor=white"
        unoptimized
      />
      <Image
        width="61"
        height="20"
        alt="Stripe"
        src="https://img.shields.io/badge/-Stripe-645CFF?style=flat-square&logo=stripe&logoColor=white"
        unoptimized
      />
      <Image
        width="47"
        height="20"
        alt="iOS"
        src="https://img.shields.io/badge/-iOS-000000?style=flat-square&logo=ios&logoColor=white"
        unoptimized
      />
      <Image
        width="67"
        height="20"
        alt="macOS"
        src="https://img.shields.io/badge/-macOS-000000?style=flat-square&logo=macos&logoColor=white"
        unoptimized
      />
      <Image
        width="69"
        height="20"
        alt="Ubuntu"
        src="https://img.shields.io/badge/-Ubuntu-E95420?style=flat-square&logo=ubuntu&logoColor=white"
        unoptimized
      />
    </div>
  );
}
